list_buah = ['blueberry', 'strawberry', 'blackberry', 'mulberry', 'raspberry']
print('list_buah:',list_buah)
list_nama = ['riflah', 'nasywa', 'isti', 'meilda', 'zikry']
print('list_nama:',list_nama)
print(list_buah[0])
print(list_buah[1])
print(list_buah[2])
print(list_buah[3])
print(list_buah[4])
print(list_nama[0])
print(list_nama[-1])
print(list_nama[-2])
print(list_nama[-3])
print(list_nama[-4])
print(list_buah[0:1])
print(list_buah[1:2])
print(list_buah[1:3])
print(list_buah[1:4])
print(list_nama[0:1])
print(list_nama[1:2])
print(list_nama[1:3])
print(list_nama[1:4])
list_buah[0] = 'dial'
print(list_buah)
list_buah.append('alpukat')
print(list_buah)
list_buah.append('melon')
print(list_buah)
list_buah.insert(0, 'jeruk')
print(list_buah)
list_buah.insert(1, 'mangga')
print(list_buah)
list_buah.insert(2, 'pisang')
print(list_buah)
list_buah.insert(3, 'leci')
print(list_buah)
list_buah.insert(4, 'pir')
print(list_buah)
list_buah.insert(0, 'timun suri')
print(list_buah)
list_buah.insert(1, 'apel')
print(list_buah)
list_buah.pop(0)
'apel'
print(list_buah)
list_buah.remove('pisang')
print(list_buah)
del list_buah[5]
print(list_buah)
del list_buah[4]
print(list_buah)
list_buah.remove('apel')
print(list_buah)
list_buah.pop(0)
'leci'
print(list_buah)
del list_buah[1]
print(list_buah)
del list_buah[1]
print(list_buah)
del list_buah[1]
print(list_buah)
del list_buah[1]
print(list_buah)
del list_buah[1]
print(list_buah)
list_buah.sort()
print(list_buah)
